exit with error if a git clone operation fails
PR from patch https://github.com/pyenv/pyenv-installer/issues/40#issuecomment-386879166 - thanks @tuxlifan

diff --git a/bin/pyenv-installer b/bin/pyenv-installer
--- a/bin/pyenv-installer
+++ b/bin/pyenv-installer
@@ -21,8 +21,13 @@ colorize() {
   fi
 }
 
+failed_checkout() {
+  echo "Failed to git clone $1"
+  exit -1
+}
+
 checkout() {
-  [ -d "$2" ] || git clone --depth 1 "$1" "$2"
+  [ -d "$2" ] || git clone --depth 1 "$1" "$2" || failed_checkout "$1"
 }
 
 if ! command -v git 1>/dev/null 2>&1; then
