Display shell configurations based on user's shell

diff --git a/bin/pyenv-installer b/bin/pyenv-installer
--- a/bin/pyenv-installer
+++ b/bin/pyenv-installer
@@ -7,12 +7,26 @@ if [ -z "$PYENV_ROOT" ]; then
   PYENV_ROOT="${HOME}/.pyenv"
 fi
 
+shell="$1"
+if [ -z "$shell" ]; then
+  shell="$(ps c -p "$PPID" -o 'ucomm=' 2>/dev/null || true)"
+  shell="${shell##-}"
+  shell="${shell%% *}"
+  shell="$(basename "${shell:-$SHELL}")"
+fi
+
+colorize() {
+  if [ -t 1 ]; then printf "\e[%sm%s\e[m" "$1" "$2"
+  else echo -n "$2"
+  fi
+}
+
 checkout() {
   [ -d "$2" ] || git clone "$1" "$2"
 }
 
 if ! command -v git 1>/dev/null 2>&1; then
-  echo "pyenv: Git is not installed, can't continue." 1>&2
+  echo "pyenv: Git is not installed, can't continue." >&2
   exit 1
 fi
 
@@ -25,15 +39,43 @@ checkout "https://github.com/yyuu/pyenv-update.git"     "${PYENV_ROOT}/plugins/p
 checkout "https://github.com/yyuu/pyenv-version-ext.git" "${PYENV_ROOT}/plugins/pyenv-version-ext"
 checkout "https://github.com/yyuu/pyenv-virtualenv.git" "${PYENV_ROOT}/plugins/pyenv-virtualenv"
 
-if ! command -v pyenv 1>/dev/null 2>&1; then
-  cat <<EOS
-Seems you still have not added 'pyenv' to the load path:
+if ! command -v pyenv 1>/dev/null; then
+  { echo
+    colorize 1 "WARNING"
+    echo ": seems you still have not added 'pyenv' to the load path."
+    echo
+  } >&2
 
-export PYENV_ROOT="\${HOME}/.pyenv"
+  case "$shell" in
+  bash )
+    profile="~/.bash_profile"
+    ;;
+  zsh )
+    profile="~/.zshrc"
+    ;;
+  ksh )
+    profile="~/.profile"
+    ;;
+  fish )
+    profile="~/.config/fish/config.fish"
+    ;;
+  * )
+    profile="your profile"
+    ;;
+  esac
 
-if [ -d "\${PYENV_ROOT}" ]; then
-  export PATH="\${PYENV_ROOT}/bin:\${PATH}"
-  eval "\$(pyenv init -)"
-fi
-EOS
+  { echo "# Load pyenv automatically by adding"
+    echo "# the following to ${profile}:"
+    echo
+    case "$shell" in
+    fish )
+      echo "set -x PATH \"\$HOME/.pyenv/bin\" \$PATH"
+      echo 'status --is-interactive; and . (pyenv init -|psub)'
+      ;;
+    * )
+      echo "export PATH=\"\$HOME/.pyenv/bin:\$PATH"
+      echo "eval \"\$(pyenv init -)\""
+      ;;
+    esac
+  } >&2
 fi
